# Generated by Django 2.0.8 on 2018-08-15 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cid', models.CharField(max_length=100)),
                ('last_seen', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cid', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('last_seen', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('module', models.CharField(max_length=1)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=9)),
                ('last_seen', models.DateTimeField()),
                ('available', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examdates.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examdates.Country')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examdates.Country'),
        ),
    ]
