# Generated by Django 2.0.8 on 2018-08-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examdates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='last_seen',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='last_seen',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='last_seen',
            field=models.DateTimeField(null=True),
        ),
    ]
