# Generated by Django 2.0.8 on 2018-08-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examdates', '0002_auto_20180815_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='venue',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
